// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: secure.proto

package securepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message.
type ServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion string                  `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind       string                  `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata   *ServerRequest_Metadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec       *ServerRequest_Spec     `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *ServerRequest) Reset() {
	*x = ServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest) ProtoMessage() {}

func (x *ServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest.ProtoReflect.Descriptor instead.
func (*ServerRequest) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{0}
}

func (x *ServerRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ServerRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ServerRequest) GetMetadata() *ServerRequest_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServerRequest) GetSpec() *ServerRequest_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// The response message.
type ServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error  string              `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Output *ServerReply_Output `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *ServerReply) Reset() {
	*x = ServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReply) ProtoMessage() {}

func (x *ServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReply.ProtoReflect.Descriptor instead.
func (*ServerReply) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{1}
}

func (x *ServerReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ServerReply) GetOutput() *ServerReply_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

type ServerRequest_Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServerRequest_Metadata) Reset() {
	*x = ServerRequest_Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRequest_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest_Metadata) ProtoMessage() {}

func (x *ServerRequest_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest_Metadata.ProtoReflect.Descriptor instead.
func (*ServerRequest_Metadata) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServerRequest_Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServerRequest_Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats  *ServerRequest_Spec_Stats  `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	Bare   *ServerRequest_Spec_Bare   `protobuf:"bytes,2,opt,name=bare,proto3" json:"bare,omitempty"`
	Docker *ServerRequest_Spec_Docker `protobuf:"bytes,3,opt,name=docker,proto3" json:"docker,omitempty"`
}

func (x *ServerRequest_Spec) Reset() {
	*x = ServerRequest_Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRequest_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest_Spec) ProtoMessage() {}

func (x *ServerRequest_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest_Spec.ProtoReflect.Descriptor instead.
func (*ServerRequest_Spec) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ServerRequest_Spec) GetStats() *ServerRequest_Spec_Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ServerRequest_Spec) GetBare() *ServerRequest_Spec_Bare {
	if x != nil {
		return x.Bare
	}
	return nil
}

func (x *ServerRequest_Spec) GetDocker() *ServerRequest_Spec_Docker {
	if x != nil {
		return x.Docker
	}
	return nil
}

type ServerRequest_Spec_Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dockers bool `protobuf:"varint,1,opt,name=dockers,proto3" json:"dockers,omitempty"`
}

func (x *ServerRequest_Spec_Stats) Reset() {
	*x = ServerRequest_Spec_Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRequest_Spec_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest_Spec_Stats) ProtoMessage() {}

func (x *ServerRequest_Spec_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest_Spec_Stats.ProtoReflect.Descriptor instead.
func (*ServerRequest_Spec_Stats) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *ServerRequest_Spec_Stats) GetDockers() bool {
	if x != nil {
		return x.Dockers
	}
	return false
}

type ServerRequest_Spec_Bare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	Sbom  bool     `protobuf:"varint,2,opt,name=sbom,proto3" json:"sbom,omitempty"`
	Vul   bool     `protobuf:"varint,3,opt,name=vul,proto3" json:"vul,omitempty"`
}

func (x *ServerRequest_Spec_Bare) Reset() {
	*x = ServerRequest_Spec_Bare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRequest_Spec_Bare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest_Spec_Bare) ProtoMessage() {}

func (x *ServerRequest_Spec_Bare) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest_Spec_Bare.ProtoReflect.Descriptor instead.
func (*ServerRequest_Spec_Bare) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *ServerRequest_Spec_Bare) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *ServerRequest_Spec_Bare) GetSbom() bool {
	if x != nil {
		return x.Sbom
	}
	return false
}

func (x *ServerRequest_Spec_Bare) GetVul() bool {
	if x != nil {
		return x.Vul
	}
	return false
}

type ServerRequest_Spec_Docker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Images []*ServerRequest_Spec_Docker_Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	Sbom   bool                               `protobuf:"varint,2,opt,name=sbom,proto3" json:"sbom,omitempty"`
	Vul    bool                               `protobuf:"varint,3,opt,name=vul,proto3" json:"vul,omitempty"`
}

func (x *ServerRequest_Spec_Docker) Reset() {
	*x = ServerRequest_Spec_Docker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRequest_Spec_Docker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest_Spec_Docker) ProtoMessage() {}

func (x *ServerRequest_Spec_Docker) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest_Spec_Docker.ProtoReflect.Descriptor instead.
func (*ServerRequest_Spec_Docker) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{0, 1, 2}
}

func (x *ServerRequest_Spec_Docker) GetImages() []*ServerRequest_Spec_Docker_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ServerRequest_Spec_Docker) GetSbom() bool {
	if x != nil {
		return x.Sbom
	}
	return false
}

func (x *ServerRequest_Spec_Docker) GetVul() bool {
	if x != nil {
		return x.Vul
	}
	return false
}

type ServerRequest_Spec_Docker_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Tag  string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *ServerRequest_Spec_Docker_Image) Reset() {
	*x = ServerRequest_Spec_Docker_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRequest_Spec_Docker_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest_Spec_Docker_Image) ProtoMessage() {}

func (x *ServerRequest_Spec_Docker_Image) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest_Spec_Docker_Image.ProtoReflect.Descriptor instead.
func (*ServerRequest_Spec_Docker_Image) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{0, 1, 2, 0}
}

func (x *ServerRequest_Spec_Docker_Image) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ServerRequest_Spec_Docker_Image) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ServerReply_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bare   *ServerReply_Output_Bare   `protobuf:"bytes,1,opt,name=bare,proto3" json:"bare,omitempty"`
	Docker *ServerReply_Output_Docker `protobuf:"bytes,2,opt,name=docker,proto3" json:"docker,omitempty"`
	Stats  *ServerReply_Output_Stats  `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *ServerReply_Output) Reset() {
	*x = ServerReply_Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReply_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReply_Output) ProtoMessage() {}

func (x *ServerReply_Output) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReply_Output.ProtoReflect.Descriptor instead.
func (*ServerReply_Output) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ServerReply_Output) GetBare() *ServerReply_Output_Bare {
	if x != nil {
		return x.Bare
	}
	return nil
}

func (x *ServerReply_Output) GetDocker() *ServerReply_Output_Docker {
	if x != nil {
		return x.Docker
	}
	return nil
}

func (x *ServerReply_Output) GetStats() *ServerReply_Output_Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ServerReply_Output_Bare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sbom string `protobuf:"bytes,1,opt,name=sbom,proto3" json:"sbom,omitempty"`
	Vul  string `protobuf:"bytes,2,opt,name=vul,proto3" json:"vul,omitempty"`
}

func (x *ServerReply_Output_Bare) Reset() {
	*x = ServerReply_Output_Bare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReply_Output_Bare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReply_Output_Bare) ProtoMessage() {}

func (x *ServerReply_Output_Bare) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReply_Output_Bare.ProtoReflect.Descriptor instead.
func (*ServerReply_Output_Bare) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *ServerReply_Output_Bare) GetSbom() string {
	if x != nil {
		return x.Sbom
	}
	return ""
}

func (x *ServerReply_Output_Bare) GetVul() string {
	if x != nil {
		return x.Vul
	}
	return ""
}

type ServerReply_Output_Docker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sbom string `protobuf:"bytes,1,opt,name=sbom,proto3" json:"sbom,omitempty"`
	Vul  string `protobuf:"bytes,2,opt,name=vul,proto3" json:"vul,omitempty"`
}

func (x *ServerReply_Output_Docker) Reset() {
	*x = ServerReply_Output_Docker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReply_Output_Docker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReply_Output_Docker) ProtoMessage() {}

func (x *ServerReply_Output_Docker) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReply_Output_Docker.ProtoReflect.Descriptor instead.
func (*ServerReply_Output_Docker) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *ServerReply_Output_Docker) GetSbom() string {
	if x != nil {
		return x.Sbom
	}
	return ""
}

func (x *ServerReply_Output_Docker) GetVul() string {
	if x != nil {
		return x.Vul
	}
	return ""
}

type ServerReply_Output_Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dockers []*ServerReply_Output_Stats_Docker `protobuf:"bytes,1,rep,name=dockers,proto3" json:"dockers,omitempty"`
}

func (x *ServerReply_Output_Stats) Reset() {
	*x = ServerReply_Output_Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReply_Output_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReply_Output_Stats) ProtoMessage() {}

func (x *ServerReply_Output_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReply_Output_Stats.ProtoReflect.Descriptor instead.
func (*ServerReply_Output_Stats) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{1, 0, 2}
}

func (x *ServerReply_Output_Stats) GetDockers() []*ServerReply_Output_Stats_Docker {
	if x != nil {
		return x.Dockers
	}
	return nil
}

type ServerReply_Output_Stats_Docker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Tag  string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *ServerReply_Output_Stats_Docker) Reset() {
	*x = ServerReply_Output_Stats_Docker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReply_Output_Stats_Docker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReply_Output_Stats_Docker) ProtoMessage() {}

func (x *ServerReply_Output_Stats_Docker) ProtoReflect() protoreflect.Message {
	mi := &file_secure_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReply_Output_Stats_Docker.ProtoReflect.Descriptor instead.
func (*ServerReply_Output_Stats_Docker) Descriptor() ([]byte, []int) {
	return file_secure_proto_rawDescGZIP(), []int{1, 0, 2, 0}
}

func (x *ServerReply_Output_Stats_Docker) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ServerReply_Output_Stats_Docker) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_secure_proto protoreflect.FileDescriptor

var file_secure_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x22, 0xa6, 0x05, 0x0a, 0x0d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x3f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x33, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x1a, 0x1e, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0xca, 0x03, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x3b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x63,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x38, 0x0a,
	0x04, 0x62, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x6c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x42, 0x61, 0x72,
	0x65, 0x52, 0x04, 0x62, 0x61, 0x72, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52,
	0x06, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x1a, 0x21, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x1a, 0x42, 0x0a, 0x04, 0x42, 0x61,
	0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x62, 0x6f, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x62, 0x6f, 0x6d, 0x12, 0x10, 0x0a, 0x03,
	0x76, 0x75, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x76, 0x75, 0x6c, 0x1a, 0xa3,
	0x01, 0x0a, 0x06, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x6c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x62, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73,
	0x62, 0x6f, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x75, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x76, 0x75, 0x6c, 0x1a, 0x2d, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65,
	0x70, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x61, 0x67, 0x22, 0xfd, 0x03, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x74,
	0x61, 0x6c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x1a, 0x9e, 0x03, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x38,
	0x0a, 0x04, 0x62, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x6c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x42, 0x61,
	0x72, 0x65, 0x52, 0x04, 0x62, 0x61, 0x72, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x52, 0x06, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x1a, 0x2c, 0x0a, 0x04, 0x42, 0x61, 0x72, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x62, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x62, 0x6f,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x75, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x76, 0x75, 0x6c, 0x1a, 0x2e, 0x0a, 0x06, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x62, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x62, 0x6f,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x75, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x76, 0x75, 0x6c, 0x1a, 0x7f, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x46, 0x0a, 0x07,
	0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x07, 0x64, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x73, 0x1a, 0x2e, 0x0a, 0x06, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65,
	0x70, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x61, 0x67, 0x32, 0x53, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x44, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_secure_proto_rawDescOnce sync.Once
	file_secure_proto_rawDescData = file_secure_proto_rawDesc
)

func file_secure_proto_rawDescGZIP() []byte {
	file_secure_proto_rawDescOnce.Do(func() {
		file_secure_proto_rawDescData = protoimpl.X.CompressGZIP(file_secure_proto_rawDescData)
	})
	return file_secure_proto_rawDescData
}

var file_secure_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_secure_proto_goTypes = []interface{}{
	(*ServerRequest)(nil),                   // 0: metalsecure.ServerRequest
	(*ServerReply)(nil),                     // 1: metalsecure.ServerReply
	(*ServerRequest_Metadata)(nil),          // 2: metalsecure.ServerRequest.Metadata
	(*ServerRequest_Spec)(nil),              // 3: metalsecure.ServerRequest.Spec
	(*ServerRequest_Spec_Stats)(nil),        // 4: metalsecure.ServerRequest.Spec.Stats
	(*ServerRequest_Spec_Bare)(nil),         // 5: metalsecure.ServerRequest.Spec.Bare
	(*ServerRequest_Spec_Docker)(nil),       // 6: metalsecure.ServerRequest.Spec.Docker
	(*ServerRequest_Spec_Docker_Image)(nil), // 7: metalsecure.ServerRequest.Spec.Docker.Image
	(*ServerReply_Output)(nil),              // 8: metalsecure.ServerReply.Output
	(*ServerReply_Output_Bare)(nil),         // 9: metalsecure.ServerReply.Output.Bare
	(*ServerReply_Output_Docker)(nil),       // 10: metalsecure.ServerReply.Output.Docker
	(*ServerReply_Output_Stats)(nil),        // 11: metalsecure.ServerReply.Output.Stats
	(*ServerReply_Output_Stats_Docker)(nil), // 12: metalsecure.ServerReply.Output.Stats.Docker
}
var file_secure_proto_depIdxs = []int32{
	2,  // 0: metalsecure.ServerRequest.metadata:type_name -> metalsecure.ServerRequest.Metadata
	3,  // 1: metalsecure.ServerRequest.spec:type_name -> metalsecure.ServerRequest.Spec
	8,  // 2: metalsecure.ServerReply.output:type_name -> metalsecure.ServerReply.Output
	4,  // 3: metalsecure.ServerRequest.Spec.stats:type_name -> metalsecure.ServerRequest.Spec.Stats
	5,  // 4: metalsecure.ServerRequest.Spec.bare:type_name -> metalsecure.ServerRequest.Spec.Bare
	6,  // 5: metalsecure.ServerRequest.Spec.docker:type_name -> metalsecure.ServerRequest.Spec.Docker
	7,  // 6: metalsecure.ServerRequest.Spec.Docker.images:type_name -> metalsecure.ServerRequest.Spec.Docker.Image
	9,  // 7: metalsecure.ServerReply.Output.bare:type_name -> metalsecure.ServerReply.Output.Bare
	10, // 8: metalsecure.ServerReply.Output.docker:type_name -> metalsecure.ServerReply.Output.Docker
	11, // 9: metalsecure.ServerReply.Output.stats:type_name -> metalsecure.ServerReply.Output.Stats
	12, // 10: metalsecure.ServerReply.Output.Stats.dockers:type_name -> metalsecure.ServerReply.Output.Stats.Docker
	0,  // 11: metalsecure.ServerProto.SendServer:input_type -> metalsecure.ServerRequest
	1,  // 12: metalsecure.ServerProto.SendServer:output_type -> metalsecure.ServerReply
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_secure_proto_init() }
func file_secure_proto_init() {
	if File_secure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_secure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRequest_Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRequest_Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRequest_Spec_Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRequest_Spec_Bare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRequest_Spec_Docker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRequest_Spec_Docker_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReply_Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReply_Output_Bare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReply_Output_Docker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReply_Output_Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReply_Output_Stats_Docker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_secure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secure_proto_goTypes,
		DependencyIndexes: file_secure_proto_depIdxs,
		MessageInfos:      file_secure_proto_msgTypes,
	}.Build()
	File_secure_proto = out.File
	file_secure_proto_rawDesc = nil
	file_secure_proto_goTypes = nil
	file_secure_proto_depIdxs = nil
}
